# Generated by Django 6.1.1 on 2026-09-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='color',
        ),
        migrations.AddField(
            model_name='sneaker',
            name='gallery',
            field=models.JSONField(blank=True, default=list, verbose_name='Галерея изображений'),
        ),
    ]
